export const Types = {
  user: {
    LOGIN_USER_SUCCESS: "LOGIN_USER_SUCCESS",
    LOGIN_USER_FAILED: "LOGIN_USER_FAILED",

    SIGNUP_USER_SUCCESS: "SIGNUP_USER_SUCCESS",
    SIGNUP_USER_FAILED: "SIGNUP_USER_FAILED",

    UPDATE_USER_SUCCESS: "UPDATE_USER_SUCCESS",
    UPDATE_USER_FAILED: "UPDATE_USER_FAILED",

    GET_USER_SUCCESS: "GET_USER_SUCCESS",
    GET_USER_FAILED: "GET_USER_FAILED",

    UPDATE_USER_SUCCESS: "UPDATE_USER_SUCCESS",
    UPDATE_USER_FAILED: "UPDATE_USER_FAILED",

    LOGOUT_USER: "LOGOUT_USER",
  },
  blog: {
    POST_BLOG_SUCCESS: "POST_BLOG_SUCCESS",
    POST_BLOG_FAILED: "POST_BLOG_FAILED",

    GET_ALL_BLOGS_SUCCESS: "GET_ALL_BLOGS_SUCCESS",
    GET_ALL_BLOGS_FAILED: "GET_ALL_BLOGS_FAILED",

    GET_MY_BLOGS_SUCCESS: "GET_MY_BLOGS_SUCCESS",
    GET_MY_BLOGS_FAILED: "GET_MY_BLOGS_FAILED",

    GET_BLOG_SUCCESS: "GET_BLOG_SUCCESS",
    GET_BLOG_LOADING: "GET_BLOG_LOADING",
    GET_BLOG_CLEAR: "GET_BLOG_CLEAR",
    GET_BLOG_FAILED: "GET_BLOG_FAILED",

    DELETE_BLOG_SUCCESS: "DELETE_BLOG_SUCCESS",
    DELETE_BLOG_FAILED: "DELETE_BLOG_FAILED",

    UPDATE_BLOG_SUCCESS: "UPDATE_BLOG_SUCCESS",
    UPDATE_BLOG_FAILED: "UPDATE_BLOG_FAILED",
  },
  comment: {
    POST_COMMENT_SUCCESS: "POST_COMMENT_SUCCESS",
    POST_COMMENT_FAILED: "POST_COMMENT_FAILED",

    GET_ALL_COMMENTS_SUCCESS: "GET_ALL_COMMENTS_SUCCESS",
    GET_ALL_COMMENTS_FAILED: "GET_ALL_COMMENTS_FAILED",

    UPDATE_COMMENTS_SUCCESS: "UPDATE_COMMENTS_SUCCESS",
    UPDATE_COMMENTS_FAILED: "UPDATE_COMMENTS_FAILED",

    DELETE_COMMENTS_SUCCESS: "DELETE_COMMENTS_SUCCESS",
    DELETE_COMMENTS_FAILED: "DELETE_COMMENTS_FAILED",
  },
  alert: {
    SET_ALERT: "SET_ALERT",
    REMOVE_ALERT: "REMOVE_ALERT",
    SET_MODAL: "SET_MODAL",
    REMOVE_MODAL: "REMOVE_MODAL",
  },
};
